# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12-browsers

set_env: &set_env
  name: Setup Environment Variables
  command: |
    if [[ $CIRCLE_PULL_REQUEST ]]
    then
      echo 'Fetching Base Commit from GitHub'
      echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
      source $BASH_ENV
      echo "export CIRCLE_PR_BASE_SHA=`curl -s https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER} | jq -r '.base.sha'`" >> $BASH_ENV
      echo 'export AFFECTED_ARGS="--base ${CIRCLE_PR_BASE_SHA}"' >> $BASH_ENV
    else
      echo 'Fetching Base Commit from Deploy Cache'
      if [[ ! -f dist/last-deploy.txt ]]
      then
        mkdir dist && git rev-parse HEAD~1 > dist/last-deploy.txt
      fi
      echo 'export AFFECTED_ARGS="--base $(cat dist/last-deploy.txt)"' >> $BASH_ENV
    fi
    source $BASH_ENV
    echo $AFFECTED_ARGS

yarn_cache: &yarn_cache
  keys:
    - node-deps-node12-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - node-deps-node12-

deploy_cache: &deploy_cache
  key: last-deploy-sha

yarn_install: &yarn_install
  name: Install Dependencies
  command: yarn install --frozen-lockfile --non-interactive

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache
      - run:
          <<: *yarn_install
      - save_cache:
          key: node-deps-node12-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
  assemble-custom:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: yarn format:check ${AFFECTED_ARGS}
  sonar-evron:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: ./node_modules/.bin/nx workspace-lint
      - run: yarn affected:lint ${AFFECTED_ARGS} --parallel
  setup-cloud:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: yarn affected:build -- ${AFFECTED_ARGS} --parallel --configuration production
      - save_cache:
          key: build-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - dist
      - store_artifacts:
          path: dist
  test-custom:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: yarn affected:test -- ${AFFECTED_ARGS} --parallel -- --ci --code-coverage
  e2e-test-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: yarn affected:e2e -- ${AFFECTED_ARGS} --configuration production -- --headless
      - store_artifacts:
          path: dist/cypress

  deploy-production-custom:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run: yarn affected -- --target deploy ${AFFECTED_ARGS}
      - run: git rev-parse HEAD > dist/last-deploy.txt
      - save_cache:
          key: last-deploy-sha
          paths:
            - dist/last-deploy.txt

workflows:
  version: 2
  dataflow:
    jobs:
      - install
      - assemble-custom:
          build_directory: ..
          requires: ['install']
          root_directory: .
          service: dataflow
          working_directory: .
      - test-custom:
          requires: ['install']
          root_directory: .
          working_directory: .
      - sonar-everon:
          requires: ['install']
      - setup-cloud:
          requires: ['install']
      - use-adhoc:
          type: approval
          filters:
            branches:
              ignore: ['master']
          requires: ['assemble-custom']
      - deploy-all-services:
          name: deploy
          command: echo "deploy-all-services step"
          requires: ['setup-cloud']
      - deploy-ui:
          name: deploy-ui
          command: echo "deploy-ui step"
          requires:
            - setup-cloud
      - elastic-indexes:
          name: elastic-indexes
          command: echo "elastic-indexes-test"
          requires: ['deploy-ui']
      - elastic-indexes2:
          adhoc: false
          command: echo "elastic-indexes-test2" 
          name: elastic-indexes-staging
      - deploy-staging-custom:
          name: deploy-staging-dataflow
          filters:
            branches:
              only: ['master']
          command: echo "deploy-staging-custom step" 
          root_directory: .
          working_directory: .
      - integration-staging:
          name: integration-staging
          command: echo "integration-staging command"
          root_directory: .
          working_directory: .
      - e2e-test-chrome:
          requires: ['install']
      - integration-test:
          name: integration-test
          command: echo "integration-test step"
      - deploy-production-custom:
          requires: 
            - assemble-custom
            - sonar-everon
            - test-custom
            - setup-cloud
            - e2e-test-chrome
          filters:
            branches:
              only: ['master']
